Wiki Home
=========

If you are new to FreeRADIUS, or wondering if it will be suitable for your requirements, please see **[[the overview and features|Overview-and-Features]]** that it provides.

Documentation
-------------
**Beginners are strongly recommended to read the short [[concepts|guide/Concepts]] page, which provides a very light overview of how the server works.**

A short introduction to RADIUS concepts, and to FreeRADIUS is available [[here|http://networkradius.com/doc/FreeRADIUS%20Technical%20Guide.pdf]].

This wiki collects a large amount of documentation relating to [[glossary|pages/glossary/]] together in one place. Pages of particular interest to newcomers will be the [[FAQ|guide/FAQ]] and [[HOWTO|guide/HOWTO]] sections, although the [[Traditional FreeRADIUS docs page|http://www.freeradius.org/doc/]] the [[docs|https://github.com/FreeRADIUS/freeradius-server/tree/master/doc]] folder included in the server distribution also include "man" pages, and other documentation.

There are many third-party web sites and HOWTO's that give advice on FreeRADIUS.  They are usually years out of date, and refer to old versions. The advice that they give is also wrong.  We **strongly** recommend that you avoid most third-party documentation.

The following is an overview of the types of information available:

* [[API and internal functions|http://doc.freeradius.org]]
* [[Building/Compiling|building/Build]]
* [[Configuration|config/Configuration files]]
* [[Base Modules|project/List of Modules]]
* Creating your own [[Modules for FreeRADIUS Version 2|contributing/Modules2]]
* Creating your own [[Modules for FreeRADIUS Version 1|contributing/Modules1]]
* [[Radius Clients|glossary/Radius Clients]]
* [[FAQ|guide/FAQ]]
* [[HOWTO|guide/HOWTO]] example setups, vendor docs, and cookbooks.
* [[glossary|pages/glossary/]]

Contributing
------------
FreeRADIUS is an open source project and as such depends on contributions from its users. Even if you don't know C you can still contribute to the project by editing documentation on the wiki, posting bugs on [[GitHub|https://github.com/FreeRADIUS/freeradius-server/issues]] or helping out on the [[users mailing list|Mailing-list#Users+list]].

If you are comfortable coding in C and have a patch or new module you'd like to see included in the main distribution, please see the [[submitting patches via GitHub|contributing/GitHub]] page for instructions on generating a 'pull request'.

For major refactoring and new modules, add an issue to [[GitHub|https://github.com/FreeRADIUS/freeradius-server/issues]], so that the core project team can comment on the proposed work.

Bug reports
-----------
If you find an issue in the server please report it so that it can be fixed in a future release. The procedure for reporting defects can be found [[here|https://github.com/FreeRADIUS/freeradius-server/blob/master/doc/bugs]].

This Wiki
---------
This Wiki is now hosted on a FreeRADIUS project server, with a gollum front end backed by "git".  It is now easier to login and make changes.  Please see the [[New Wiki]] Page for details.

.. A read only version of the wiki can be checked out using git::
.. 
..     git clone git://git.freeradius.org/wiki.freeradius.org.git
.. (note, doesn't currently work)
