What is accounting?
-------------------

Accounting refers to the tracking of the consumption of [[NAS]] resources by users. This information may be used for management, planning, billing, or other purposes.

Typical information that is gathered in accounting is the identity of the user, the nature of the service delivered, when the service began, and when it ended.

Real-Time
=========
Real-time accounting refers to accounting information that is delivered concurrently with the consumption of the resources.  

Batch
=====
Batch accounting refers to accounting information that is saved until it is delivered at a later time.

See Also
========
* RFC 2866
* [[AAA]]
* [[AAAA]]