:doc:`glossary/FreeRADIUS` is the premiere open source [[RADIUS]] server. While detailed statistics are not available, we believe that [[FreeRADIUS]] is well within the top five [[RADIUS]] servers world-wide, in terms of the number of people who use it daily for authentication. It scales from embedded systems with small amounts of memory, to systems with millions of users. It is fast, flexible, configurable, and supports more authentication protocols than many commercial servers.