The FreeRADIUS Project is the result of the work done by a large number of people. 

We would like to publicly thank the following major contributors:

+------------------------------+-----------------------------------------------------------+----------------+
|     Contributor              |                         Details                           |     Active     |
+==============================+===========================================================+================+
| Adrian Pavlykevych           | Wrote the original pre v3 rlm_ldap module.                | no             |
+------------------------------+-----------------------------------------------------------+----------------+
| Arran Cudbard-Bell           | - FreeRADIUS maintainer.                                  | yes            |
| http://www.rm-rfi.com        | - Wrote rlm_rest.                                         |                |
| http://github.com/arr2036    | - Rewrote v3 rlm_krb5.                                    |                |
|                              | - Rewrote v3 rlm_sql acct.                                |                |
|                              | - Added the neat parts of v3 rlm_cache.                   |                |
|                              | - Added v3 rlm_ldap update support.                       |                |
|                              | - Maintains the wiki.                                     |                |
|                              | - Helps maintain the build system.                        |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Alan Curry                   | Contributed many patches for proxying, replication,       | no             |
|                              | realm support.                                            |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Alan DeKok                   | - FreeRADIUS Project Lead.                                | yes            |
| http://www.freeradius.org    | - Registered and maintains freeradius.org.                |                |
| http://www.networkradius.com | - Wrote the module code.                                  |                |
| http://github.com/alandekok  | - Made the server threaded.                               |                |
|                              | - Rewrote and refactored the majority of the server core. |                |
|                              | - Wrote and contributed to many modules.                  |                |
|                              | - Maintains the build system.                             |                |
|                              | - Is the CEO of Network RADIUS                            |                |
|                              |   (a commercial entity representing the project).         |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Brandon Lee Poyner           | Netscape-MTA-MD5 authentication module.                   | no             |
+------------------------------+-----------------------------------------------------------+----------------+
| Chris Brotsos                | Memory allocation debugging and proxy enhancements.       | no             |
+------------------------------+-----------------------------------------------------------+----------------+
| Chris Parker                 | - Configuration parser enhancements.                      | no             |
|                              | - Proxy enhancements.                                     |                |
|                              | - Wrote rlm_attr_filter                                   |                |
|                              | - FreeRADIUS Client embedded mode and other enhancements. |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Jeff Carneal of              | Wrote the caching support for the Unix module.            | no             |
| Apex Internet                |                                                           |                |
| Services, Inc.               |                                                           |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Jochen Friedrich             | v1 SMUX / SNMP support (since removed).                   | no             |
+------------------------------+-----------------------------------------------------------+----------------+
| John Dennis                  | Maintains RHEL RPMs and acts as liaison with RH.          | yes            |
+------------------------------+-----------------------------------------------------------+----------------+
| Kostas Kalevras              | Contributed the 'dialup_admin' PHP server administration  | no             |
|                              | code.                                                     |                |
+------------------------------+-----------------------------------------------------------+----------------+ 
| Matthew Newton               | Many patches and bug fixes.                               | yes            |
| http://github.com/mcnewton   |                                                           |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Miquel van                   | Wrote the original Cistron server, and started the        | no             |
| Smoorenburg                  | FreeRADIUS source tree.                                   |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Mike Machado                 | Author of the SQL module.                                 | no             |
+------------------------------+-----------------------------------------------------------+----------------+
| Miguel a.l. Paraz            | Wrote the original code which was the basis for the       | no             |
|                              | PAM module.                                               |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Nathan Neulinger             | pre v3 rlm_krb5                                           | no             |
+------------------------------+-----------------------------------------------------------+----------------+
| Peter Nixon                  | Maintains rlm_sqlippool and hacks on other SQL related    | yes            |
| http://www.peternixon.net    | code, maintains openSUSE binary packages.                 |                |
+------------------------------+-----------------------------------------------------------+----------------+
| Phil Mayers                  | - Wrote the SoH code.                                     | yes            |
| http://github.com/philmayers | - Added many enhancements to rlm_eap.                     |                |
|                              | - Started the code documentation effort.                  |                |
+------------------------------+-----------------------------------------------------------+----------------+

The following individuals also get honourable mentions for contributing significantly to the wiki or mailing list:

+------------------------------+-----------------------------------------------------------+----------------+
|     Contributor              |                         Details                           |     Active     |
+==============================+===========================================================+================+
| Alan Buxey                   | For services to FreeRADIUS users.                         | yes            |
+------------------------------+-----------------------------------------------------------+----------------+
| Alex Clouter                 | For services to FreeRADIUS users.                         | no (lost to    |
|                              |                                                           | the dark side) |
+------------------------------+-----------------------------------------------------------+----------------+
| Brian Candler                | For services to FreeRADIUS users.                         | yes            |
+------------------------------+-----------------------------------------------------------+----------------+
| Fajar A Nugraha              | For services to FreeRADIUS users.                         | yes            |
+------------------------------+-----------------------------------------------------------+----------------+
| Kevin Bonner                 | For services to FreeRADIUS users, and the wiki.           | no             |
+------------------------------+-----------------------------------------------------------+----------------+