Configuration files
===================

For every part of FreeRADIUS, in the configuration directory (``/etc/raddb``, ``/etc/freeradius`` or similar) there is a fully commented example file included, that explains what it does, and how to use it. Read those sample files too!

Again, many of the configuration files are **ONLY** documented in the comments included in the files.

Reading the configuration files is **REQUIRED** to fully understand how to create complex configurations of the server.

Main configuration files
------------------------

* [[radiusd.conf|https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/radiusd.conf.in]]
* [[clients.conf|https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/clients.conf]]
* [[modules configuration|pages/modules/]]
* [[sites configuration|config/sites configuration]]
* [[proxy.conf|https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/proxy.conf]]
* [[policy.d|https://github.com/FreeRADIUS/freeradius-server/tree/v3.0.x/raddb/policy.d]] (previously ``policy.conf`` in v2)

Common module configuration
---------------------------

* [[users|https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-config/files/authorize]]
* [[hints|https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-config/preprocess/hints]]
* [[huntgroups|https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/raddb/mods-config/preprocess/huntgroups]]

General configuration references
--------------------------------

* [[unlang|http://freeradius.org/radiusd/man/unlang.html]]
* [[rlm_files operators|config/Operators]]
* [[List of xlats|config/Xlat]]
* [[Virtual servers|config/Virtual server]]
* [[Module load-balancing|config/Load balancing]]
* [[Module fail-over|config/Fail over]]
* [[Users file|config/Users]]
* [[Huntgroups|config/Huntgroups]]
* [[Hints|config/Hints]]
* [[Proxying|config/Proxy]]
* [[Templates|config/Templates]]



