Debian Packages
=============

**Note:** This page is only relevant for Debian Wheezy (7.0). The version in wheezy-backports is the same as the version in Debian Jessie (8.0).

To install up-to-date FreeRADIUS 2.2.x packages on Debian stable systems, use the backports repository. For example:

* Add a [[backports mirror|http://backports.debian.org/Mirrors/]] to ``/etc/apt/sources.list`` like this:
::

 deb http://backports.debian.org/debian-backports wheezy-backports main

* Update the package indices:
::

 sudo apt-get update

* Install FreeRADIUS packages:
::

 sudo apt-get -t wheezy-backports install freeradius

* If everything went all right, make sure you will upgrade these from the same repository, by pinning it through ``/etc/apt/preferences`` like this:
::

  Package: freeradius
  Pin: release a=wheezy-backports
  Pin-Priority: 500

  Package: freeradius-common
  Pin: release a=wheezy-backports
  Pin-Priority: 500

  [...]


Add whichever other FR package you are using to the list in the same format.

See also
----------

* [[How to build Debian packages of FreeRADIUS|Build#Building Debian packages]]
