Introduction
------------

This document describes how to set up FreeRADIUS server in order to authenticate Windows XP network users transparently against Active Directory.

It is a step by step 'quick & dirty' guide to configure FreeRADIUS server, Network Access Points and Windows XP supplicants.

Principles
==========

sdfsdf

::
  comment = Home Directories
  browseable = no
  writable = yes

sdfsdf