Cookbook - Recipes and Examples
==========================

FR Configuration
^^^^^^^^^^^^
* [[Configuration files]]
* [[Mac-Auth]]
* [[LDAP-Auth Example]]

Device configuration examples
^^^^^^^^^^^^^^^^^^^^^^
* [[HP ProCurve|HP]]
* [[Cisco]]
* [[Linksys]]

Recipes for 3rd party software
^^^^^^^^^^^^^^^^^^^^^^
* [[guide/PopTop HOWTO]]
* [[Git]]
